### ISSUE TITLE
Illuminate\Cache is not compatible with Lumen

### ISSUE THREAD

**Issue by MarcFRICOU** [laravel-doctrine/orm#101]
I'm getting this error since `1.0.10`

```
[Illuminate\Contracts\Container\BindingResolutionException]
  Unresolvable dependency resolving [Parameter #0 [ <required> $app ]] in class Illuminate\Cache\CacheManager
```

It seems that `Illuminate\Cache\CacheManager` has a dependency with `Illuminate\Foundation\Application` that does not exist in lumen (it's `Laravel\Lumen\Application`). I think that `illuminate/cache` package is not compatible with Lumen

**Comment by patrickbrouwers** [comment]
Did you register the CacheServiceProvider ?

**Comment by boedy** [comment]
I'm getting the same error.

**Comment by patrickbrouwers** [comment]
Could one of you answer my question ;)

**Comment by boedy** [comment]
I'm not sure which provider you're referring to. Do you mean this provider?:

`$app->register('\Illuminate\Cache\CacheServiceProvider');`

This doesn't work.

**Comment by MarcFRICOU** [comment]
Sorry i was long to respond. Even with `CacheServiceProvider` registered, it does not work. I do think it's because of `Illuminate\Foundation\Application` dependency.

**Comment by patrickbrouwers** [comment]
Apparently the `CacheManager` is only bound to `cache` in the container, which means it's not possible to inject it as class (which sucks). So I will have to figure something out.

**Comment by MarcFRICOU** [comment]
thanks for the reply, I lock my composer dependency to `1.0.9` for now

**Comment by patrickbrouwers** [comment]
If you wait 10 minutes, I will have a fix out :)

Edit: 1.0.11 is tagged

**Comment by MarcFRICOU** [comment]
It does not work neither :cry: :

```
[ErrorException]
  Argument 1 passed to LaravelDoctrine\ORM\Configuration\Cache\ApcCacheProvider::__construct() must be an instance of Illuminate\Cache\CacheManager, instance of Illuminate\Support\Facades\Cache given
```

This time, it seems that TypeHint is not respected for Apc / Memcached / Redis and VoidCache providers

**Comment by patrickbrouwers** [comment]
Works for Redis for me. 
I do have facade disabled though.

**Comment by patrickbrouwers** [comment]
Can't reproduce with facades enabled and driver set to APC

**Comment by MarcFRICOU** [comment]
I'll look into it, it must come from my configuration

**Comment by patrickbrouwers** [comment]
Let me know

**Comment by MarcFRICOU** [comment]
So, for now, after providers registering rearrangement (1st `CacheServiceProvider` then `DoctrineServiceProvider`) with `php artisan` I have a infinite loop on `Laravel\Lumen\Application->registerCacheBindings()`

**Comment by patrickbrouwers** [comment]
Perhaps it's not necessary to register CacheServiceProvider separately?

**Comment by MarcFRICOU** [comment]
without CacheServiceProvider

```
 [ReflectionException]
  Class cache does not exist
```

**Comment by patrickbrouwers** [comment]
Hm, this part of Lumen is really crap :(

**Comment by MarcFRICOU** [comment]
Well, that's work over HTTP if I register in good order the different providers. But I can't make it work in console with `php artisan`

**Comment by patrickbrouwers** [comment]
I'm a bit busy now, but later today I might have time to look into the Cache Factory interface and see if that might me a better solution.

**Comment by MarcFRICOU** [comment]
I have a solution, I don't understand why for now, it's crapy, but it's work. In `DoctrineServiceProvider` i made this change :

```
    /**
     * Register the cache drivers
     */
    protected function setupCache()
    {
        if ($this->isLumen()) {
            // Alias the cache, so the class is injectable in Lumen too
            $this->app->alias('cache', \Illuminate\Cache\CacheManager::class);

            $this->app->make('cache');
        }


        // Bind Doctrine CacheManager
        $this->app->singleton(CacheManager::class);
    }
```

I think that it's because of `registerCacheBindings` in `Application`. It's done after registering `DoctrineServiceProvider` so cache is not already bound :confused:.

I had to remove `CacheServiceProvider` registering because it's exactly what is done by `registerCacheBindings`

**Comment by MarcFRICOU** [comment]
Later in the afternoon, i could make a PR if you want.

**Comment by patrickbrouwers** [comment]
Found a better solution

**Comment by MarcFRICOU** [comment]
:+1: much more efficient and smart :wink: (fixed in 1.0.12)

**Comment by khlipeng** [comment]
in bootstrap/app.php add:

$app->alias('cache', 'Illuminate\Cache\CacheManager');
$app->alias('auth', 'Illuminate\Auth\AuthManager');

**Comment by patrickbrouwers** [comment]
@khlipeng those aliases shouldn't be necessary anymore. It was fixed in November and shouldn't be a problem anymore.

**Comment by rannien** [comment]
@patrickbrouwers yes but this 'bug' is still exists, I have a fresh lumen installation and I am still getting that error without the app.php fixes

**Comment by patrickbrouwers** [comment]
Then you are on an old version. I'm using Lumen 5.2 myself with redis cache enabled.

**Comment by rannien** [comment]
I'm using v5.2.6 lumen
![screenshot 4](https://cloud.githubusercontent.com/assets/2854597/15093178/de6c9cc4-147f-11e6-9ebb-92d84b46267b.png)

**Comment by patrickbrouwers** [comment]
I was referring to the Laravel-Doctrine package

**Comment by rannien** [comment]
Ah, sorry I misunderstood
