### ISSUE TITLE
Installation issue with Laravel 7.12

### ISSUE THREAD

**Issue by ghostal** [laravel-doctrine/orm#445]
Since version 7.11 (https://github.com/laravel/framework/commit/95b34d42aad703cef6a64077b11eaf208ff421ed), Laravel has changed it's dependencies from requiring `"doctrine/inflector": "^1.1"` to requiring `"doctrine/inflector": "^1.4|^2.0"`.

The latest version of `doctrine/common` has the dependency `"doctrine/inflector": "^1.0"`.

This means the following happens:

```
alex@desktop:~/tmp$ composer create-project --prefer-dist laravel/framework blog
Installing laravel/framework (v7.12.0)
  - Installing laravel/framework (v7.12.0): Loading from cache
Created project in blog
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 95 installs, 0 updates, 0 removals
  - Installing hamcrest/hamcrest-php (v2.0.0): Loading from cache
  - Installing mockery/mockery (1.3.1): Loading from cache
  - Installing doctrine/inflector (2.0.1): Loading from cache

... 

  - Installing symfony/cache (v5.0.8): Downloading (100%)         
laravel/framework suggests installing ext-memcached (Required to use the memcache cache driver.)

...

predis/predis suggests installing ext-phpiredis (Allows faster serialization and deserialization of the Redis protocol)
Package moontoast/math is abandoned, you should avoid using it. Use brick/math instead.
Writing lock file
Generating autoload files
alex@desktop:~/tmp$ cd blog
alex@desktop:~/tmp/blog$ composer require laravel-doctrine/orm
Using version ^1.6 for laravel-doctrine/orm
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: remove doctrine/inflector 2.0.1
    - Conclusion: don't install doctrine/inflector 2.0.1
    - laravel-doctrine/orm 1.6.0 requires doctrine/orm ^2.6|^2.7 -> satisfiable by doctrine/orm[2.6.x-dev, 2.7.x-dev, 2.8.x-dev, v2.6.0, v2.6.1, v2.6.2, v2.6.3, v2.6.4, v2.6.5, v2.6.6, v2.7.0, v2.7.1, v2.7.2].
    - laravel-doctrine/orm 1.6.x-dev requires doctrine/orm ^2.6|^2.7 -> satisfiable by doctrine/orm[2.6.x-dev, 2.7.x-dev, 2.8.x-dev, v2.6.0, v2.6.1, v2.6.2, v2.6.3, v2.6.4, v2.6.5, v2.6.6, v2.7.0, v2.7.1, v2.7.2].
    - doctrine/orm 2.6.x-dev requires doctrine/common ^2.7.1 -> satisfiable by doctrine/common[2.10.x-dev, 2.11.x-dev, 2.12.0, 2.12.x-dev, 2.13.0, 2.13.x-dev, 2.7.x-dev, 2.8.x-dev, 2.9.x-dev, v2.10.0, v2.11.0, v2.7.1, v2.7.2, v2.7.3, v2.8.0, v2.8.1, v2.9.0].
    - doctrine/orm v2.6.0 requires doctrine/common ^2.7.1 -> satisfiable by doctrine/common[2.10.x-dev, 2.11.x-dev, 2.12.0, 2.12.x-dev, 2.13.0, 2.13.x-dev, 2.7.x-dev, 2.8.x-dev, 2.9.x-dev, v2.10.0, v2.11.0, v2.7.1, v2.7.2, v2.7.3, v2.8.0, v2.8.1, v2.9.0].
    - doctrine/orm v2.6.1 requires doctrine/common ^2.7.1 -> satisfiable by doctrine/common[2.10.x-dev, 2.11.x-dev, 2.12.0, 2.12.x-dev, 2.13.0, 2.13.x-dev, 2.7.x-dev, 2.8.x-dev, 2.9.x-dev, v2.10.0, v2.11.0, v2.7.1, v2.7.2, v2.7.3, v2.8.0, v2.8.1, v2.9.0].
    - doctrine/orm v2.6.2 requires doctrine/common ^2.7.1 -> satisfiable by doctrine/common[2.10.x-dev, 2.11.x-dev, 2.12.0, 2.12.x-dev, 2.13.0, 2.13.x-dev, 2.7.x-dev, 2.8.x-dev, 2.9.x-dev, v2.10.0, v2.11.0, v2.7.1, v2.7.2, v2.7.3, v2.8.0, v2.8.1, v2.9.0].
    - doctrine/orm v2.6.3 requires doctrine/common ^2.7.1 -> satisfiable by doctrine/common[2.10.x-dev, 2.11.x-dev, 2.12.0, 2.12.x-dev, 2.13.0, 2.13.x-dev, 2.7.x-dev, 2.8.x-dev, 2.9.x-dev, v2.10.0, v2.11.0, v2.7.1, v2.7.2, v2.7.3, v2.8.0, v2.8.1, v2.9.0].
    - doctrine/orm v2.6.4 requires doctrine/common ^2.7.1 -> satisfiable by doctrine/common[2.10.x-dev, 2.11.x-dev, 2.12.0, 2.12.x-dev, 2.13.0, 2.13.x-dev, 2.7.x-dev, 2.8.x-dev, 2.9.x-dev, v2.10.0, v2.11.0, v2.7.1, v2.7.2, v2.7.3, v2.8.0, v2.8.1, v2.9.0].
    - doctrine/orm v2.6.5 requires doctrine/common ^2.7.1 -> satisfiable by doctrine/common[2.10.x-dev, 2.11.x-dev, 2.12.0, 2.12.x-dev, 2.13.0, 2.13.x-dev, 2.7.x-dev, 2.8.x-dev, 2.9.x-dev, v2.10.0, v2.11.0, v2.7.1, v2.7.2, v2.7.3, v2.8.0, v2.8.1, v2.9.0].
    - doctrine/orm v2.6.6 requires doctrine/common ^2.7.1 -> satisfiable by doctrine/common[2.10.x-dev, 2.11.x-dev, 2.12.0, 2.12.x-dev, 2.13.0, 2.13.x-dev, 2.7.x-dev, 2.8.x-dev, 2.9.x-dev, v2.10.0, v2.11.0, v2.7.1, v2.7.2, v2.7.3, v2.8.0, v2.8.1, v2.9.0].
    - doctrine/orm 2.7.x-dev requires doctrine/common ^2.11 -> satisfiable by doctrine/common[2.11.x-dev, 2.12.0, 2.12.x-dev, 2.13.0, 2.13.x-dev, v2.11.0].
    - doctrine/orm 2.8.x-dev requires doctrine/common ^2.11 -> satisfiable by doctrine/common[2.11.x-dev, 2.12.0, 2.12.x-dev, 2.13.0, 2.13.x-dev, v2.11.0].
    - doctrine/orm v2.7.0 requires doctrine/common ^2.11 -> satisfiable by doctrine/common[2.11.x-dev, 2.12.0, 2.12.x-dev, 2.13.0, 2.13.x-dev, v2.11.0].
    - doctrine/orm v2.7.1 requires doctrine/common ^2.11 -> satisfiable by doctrine/common[2.11.x-dev, 2.12.0, 2.12.x-dev, 2.13.0, 2.13.x-dev, v2.11.0].
    - doctrine/orm v2.7.2 requires doctrine/common ^2.11 -> satisfiable by doctrine/common[2.11.x-dev, 2.12.0, 2.12.x-dev, 2.13.0, 2.13.x-dev, v2.11.0].
    - doctrine/common 2.10.x-dev requires doctrine/inflector ^1.0 -> satisfiable by doctrine/inflector[1.0.x-dev, 1.1.x-dev, 1.2.x-dev, 1.3.x-dev, 1.4.0, 1.4.1, 1.4.x-dev].
    - doctrine/common 2.11.x-dev requires doctrine/inflector ^1.0 -> satisfiable by doctrine/inflector[1.0.x-dev, 1.1.x-dev, 1.2.x-dev, 1.3.x-dev, 1.4.0, 1.4.1, 1.4.x-dev].
    - doctrine/common 2.12.0 requires doctrine/inflector ^1.0 -> satisfiable by doctrine/inflector[1.0.x-dev, 1.1.x-dev, 1.2.x-dev, 1.3.x-dev, 1.4.0, 1.4.1, 1.4.x-dev].
    - doctrine/common 2.12.x-dev requires doctrine/inflector ^1.0 -> satisfiable by doctrine/inflector[1.0.x-dev, 1.1.x-dev, 1.2.x-dev, 1.3.x-dev, 1.4.0, 1.4.1, 1.4.x-dev].
    - doctrine/common 2.13.0 requires doctrine/inflector ^1.0 -> satisfiable by doctrine/inflector[1.0.x-dev, 1.1.x-dev, 1.2.x-dev, 1.3.x-dev, 1.4.0, 1.4.1, 1.4.x-dev].
    - doctrine/common 2.13.x-dev requires doctrine/inflector ^1.0 -> satisfiable by doctrine/inflector[1.0.x-dev, 1.1.x-dev, 1.2.x-dev, 1.3.x-dev, 1.4.0, 1.4.1, 1.4.x-dev].
    - doctrine/common 2.7.x-dev requires doctrine/inflector 1.* -> satisfiable by doctrine/inflector[1.0.x-dev, 1.1.x-dev, 1.2.x-dev, 1.3.x-dev, 1.4.0, 1.4.1, 1.4.x-dev].
    - doctrine/common 2.8.x-dev requires doctrine/inflector 1.* -> satisfiable by doctrine/inflector[1.0.x-dev, 1.1.x-dev, 1.2.x-dev, 1.3.x-dev, 1.4.0, 1.4.1, 1.4.x-dev].
    - doctrine/common 2.9.x-dev requires doctrine/inflector ^1.0 -> satisfiable by doctrine/inflector[1.0.x-dev, 1.1.x-dev, 1.2.x-dev, 1.3.x-dev, 1.4.0, 1.4.1, 1.4.x-dev].
    - doctrine/common v2.10.0 requires doctrine/inflector ^1.0 -> satisfiable by doctrine/inflector[1.0.x-dev, 1.1.x-dev, 1.2.x-dev, 1.3.x-dev, 1.4.0, 1.4.1, 1.4.x-dev].
    - doctrine/common v2.11.0 requires doctrine/inflector ^1.0 -> satisfiable by doctrine/inflector[1.0.x-dev, 1.1.x-dev, 1.2.x-dev, 1.3.x-dev, 1.4.0, 1.4.1, 1.4.x-dev].
    - doctrine/common v2.7.1 requires doctrine/inflector 1.* -> satisfiable by doctrine/inflector[1.0.x-dev, 1.1.x-dev, 1.2.x-dev, 1.3.x-dev, 1.4.0, 1.4.1, 1.4.x-dev].
    - doctrine/common v2.7.2 requires doctrine/inflector 1.* -> satisfiable by doctrine/inflector[1.0.x-dev, 1.1.x-dev, 1.2.x-dev, 1.3.x-dev, 1.4.0, 1.4.1, 1.4.x-dev].
    - doctrine/common v2.7.3 requires doctrine/inflector 1.* -> satisfiable by doctrine/inflector[1.0.x-dev, 1.1.x-dev, 1.2.x-dev, 1.3.x-dev, 1.4.0, 1.4.1, 1.4.x-dev].
    - doctrine/common v2.8.0 requires doctrine/inflector 1.* -> satisfiable by doctrine/inflector[1.0.x-dev, 1.1.x-dev, 1.2.x-dev, 1.3.x-dev, 1.4.0, 1.4.1, 1.4.x-dev].
    - doctrine/common v2.8.1 requires doctrine/inflector 1.* -> satisfiable by doctrine/inflector[1.0.x-dev, 1.1.x-dev, 1.2.x-dev, 1.3.x-dev, 1.4.0, 1.4.1, 1.4.x-dev].
    - doctrine/common v2.9.0 requires doctrine/inflector ^1.0 -> satisfiable by doctrine/inflector[1.0.x-dev, 1.1.x-dev, 1.2.x-dev, 1.3.x-dev, 1.4.0, 1.4.1, 1.4.x-dev].
    - Can only install one of: doctrine/inflector[1.4.0, 2.0.1].
    - Can only install one of: doctrine/inflector[1.4.1, 2.0.1].
    - Can only install one of: doctrine/inflector[1.4.x-dev, 2.0.1].
    - Can only install one of: doctrine/inflector[1.0.x-dev, 2.0.1].
    - Can only install one of: doctrine/inflector[1.1.x-dev, 2.0.1].
    - Can only install one of: doctrine/inflector[1.2.x-dev, 2.0.1].
    - Can only install one of: doctrine/inflector[1.3.x-dev, 2.0.1].
    - Installation request for doctrine/inflector (locked at 2.0.1, required as ^1.4|^2.0) -> satisfiable by doctrine/inflector[2.0.1].
    - Installation request for laravel-doctrine/orm ^1.6 -> satisfiable by laravel-doctrine/orm[1.6.0, 1.6.x-dev].


Installation failed, reverting ./composer.json to its original content.
alex@desktop:~/tmp/blog$ 
```

If you downgrade `doctrine/inflector` to `1.4` though, you can successfully install both:

```
alex@desktop:~/tmp$ composer create-project --prefer-dist laravel/framework blog
Installing laravel/framework (v7.12.0)
  - Installing laravel/framework (v7.12.0): Loading from cache
Created project in blog
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 95 installs, 0 updates, 0 removals
  - Installing hamcrest/hamcrest-php (v2.0.0): Loading from cache
  - Installing mockery/mockery (1.3.1): Loading from cache
  - Installing doctrine/inflector (2.0.1): Loading from cache

... 

  - Installing symfony/cache (v5.0.8): Downloading (100%)         
laravel/framework suggests installing ext-memcached (Required to use the memcache cache driver.)

...

predis/predis suggests installing ext-phpiredis (Allows faster serialization and deserialization of the Redis protocol)
Package moontoast/math is abandoned, you should avoid using it. Use brick/math instead.
Writing lock file
Generating autoload files
alex@desktop:~/tmp$ cd blog
alex@desktop:~/tmp/blog$ composer require "doctrine/inflector:^1.4"
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 0 installs, 1 update, 0 removals
  - Downgrading doctrine/inflector (2.0.1 => 1.4.1): Loading from cache
Package moontoast/math is abandoned, you should avoid using it. Use brick/math instead.
Writing lock file
Generating autoload files
alex@desktop:~/tmp/blog$ composer require laravel-doctrine/orm
Using version ^1.6 for laravel-doctrine/orm
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 9 installs, 0 updates, 0 removals
  - Installing ocramius/package-versions (1.4.2): Loading from cache
  - Installing symfony/serializer (v5.0.8): Downloading (100%)         
  - Installing doctrine/annotations (1.10.2): Loading from cache
  - Installing doctrine/reflection (1.2.1): Loading from cache
  - Installing doctrine/collections (1.6.4): Loading from cache
  - Installing doctrine/persistence (1.3.7): Loading from cache
  - Installing doctrine/common (2.13.0): Loading from cache
  - Installing doctrine/orm (v2.7.2): Loading from cache
  - Installing laravel-doctrine/orm (1.6.0): Downloading (100%)         
symfony/serializer suggests installing symfony/property-info (To deserialize relations.)
symfony/serializer suggests installing symfony/yaml (For using the default YAML mapping loader.)
symfony/serializer suggests installing symfony/config (For using the XML mapping loader.)
symfony/serializer suggests installing symfony/property-access (For using the ObjectNormalizer.)
doctrine/orm suggests installing symfony/yaml (If you want to use YAML Metadata Mapping Driver)
laravel-doctrine/orm suggests installing laravel-doctrine/fluent (Fluent mapping driver (alternative to xml, yaml, ... (~1.1).)
laravel-doctrine/orm suggests installing laravel-doctrine/acl (to integrate Doctrine roles & permissions with Laravel's Authorization system (~1.0))
laravel-doctrine/orm suggests installing laravel-doctrine/extensions (to add Behavioral and Query/Type Extensions for Laravel Doctrine (~1.0))
laravel-doctrine/orm suggests installing laravel-doctrine/migrations (to add support for migrations in Laravel Doctrine (~1.0))
laravel-doctrine/orm suggests installing yajra/laravel-oci8 (Support for Laravel native queue and session database drivers in Oracle (~2.0).)
Package moontoast/math is abandoned, you should avoid using it. Use brick/math instead.
Writing lock file
Generating autoload files
ocramius/package-versions:  Generating version class...
ocramius/package-versions: ...done generating version class
alex@desktop:~/tmp/blog$ 
```

Not sure if this is something that can be easily solved another way.

I'm guessing the problem with the first approach is that `composer` can't resolve the dependency conflict because the `2.0.1` version of `doctrine/inflector` is already in the lock file, but I may be incorrect on that - I haven't had a great deal of practise with resolving dependency conflicts such as this.

**Comment by dpslwk** [comment]
Laravel change was made in v6.18.14 and v7.11.0
where they allowed `doctrine/inflector` `^2.0`

`laravel-doctrine/orm` does not explicitly include `doctrine/inflector`, just `doctrine/common` which still only calls for `"doctrine/inflector": "^1.0",`

until some patch is made to move `laravel-doctrine` to newer version of inflector
best advice is going to be either 

1. pin inflector `composer require "doctrine/inflector:^1.4"` before install `laravel-doctrine`
or 
2. remove the lock file and the vendor folder before doing `composer require laravel-doctrine/orm` which will result in composer working out on its own that it can use inflector 1.4, without needing the pin

**Comment by vv12131415** [comment]
@dpslwk maybe it needs to be also mentioned in composer/composer repo? So in next versions composer can automatically install downgraded version and not throw Error

**Comment by VottusCode** [comment]
> Laravel change was made in v6.18.14 and v7.11.0
> where they allowed `doctrine/inflector` `^2.0`
> 
> `laravel-doctrine/orm` does not explicitly include `doctrine/inflector`, just `doctrine/common` which still only calls for `"doctrine/inflector": "^1.0",`
> 
> until some patch is made to move `laravel-doctrine` to newer version of inflector
> best advice is going to be either
> 
> 1. pin inflector `composer require "doctrine/inflector:^1.4"` before install `laravel-doctrine`
>    or
> 2. remove the lock file and the vendor folder before doing `composer require laravel-doctrine/orm` which will result in composer working out on its own that it can use inflector 1.4, without needing the pin

I have the same issue, and I guess anyone using latest Laravel will have this issue, and both of the above methods by @dpslwk work just fine.

**Comment by eigan** [comment]
Fixed by allowing doctrine 2.8. This causes some BC break (from doctrine/persistence). It is handled in the WIP `2.0` branch.

**Comment by kosten** [comment]
If somebody still getting such error after command `composer require "laravel-doctrine/orm:1.7.*"`:

` Problem 1
    - laravel-doctrine/orm[1.7.3, ..., 1.7.x-dev] require doctrine/inflector ^1.4 -> found doctrine/inflector[1.4.0, ..., 1.4.x-dev] but the package is fixed to 2.0.3 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - laravel-doctrine/orm[1.7.0, ..., 1.7.2] require php ^7.3 -> your php version (8.0.2) does not satisfy that requirement.
    - Root composer.json requires laravel-doctrine/orm 1.7.* -> satisfiable by laravel-doctrine/orm[1.7.0, ..., 1.7.x-dev].
`

Just try to remove composer.lock file and try again.
In my case it has solve the issue.

**Comment by eigan** [comment]
Closing as there is really nothing we can do until doctrine allows doctrine/inflector 2.0. 

Recommended installtion method of laravel-doctrine/orm is now like this:
``` 
composer require laravel-doctrine/orm doctrine/inflector:"^1.4|^2.0"
```
