### ISSUE TITLE
Authentication: Driver [doctrine] not supported.

### ISSUE THREAD

**Issue by shssoichiro** [laravel-doctrine/orm#45]
I'm attempting to set up user authentication as per http://www.laraveldoctrine.org/docs/1.0/orm/auth. However, upon setting `'driver' => 'doctrine'` in `config/auth.php`, all routes and CLI commands now give the following error:

    [InvalidArgumentException]        
    Driver [doctrine] not supported.

As far as I can tell I have the service provider and all facades for Laravel Doctrine registered. Is there something that I'm missing or is this an actual bug? I am using laravel-doctrine/orm 1.0.1

**Comment by gpassarelli** [comment]
+1
I'm having the same issue as you when I try to enable the **LoggableExtension** and **BlameableExtension** extension

**Comment by patrickbrouwers** [comment]
@shssoichiro if you join us on slack, I will shortly be helping @gpassarelli with this

**Comment by patrickbrouwers** [comment]
Fixed by https://github.com/laravel-doctrine/orm/commit/d74d5c8f809e5608c727a90b812793ff689e7086

**Comment by pgaharwar** [comment]
Still getting this error when I do:
view()->share('user', \Auth::user());

Here is the error:
[InvalidArgumentException]
Driver [doctrine] not supported.
