### ISSUE TITLE
[QUESTION] Laravel 8 support

### ISSUE THREAD

**Issue by 99hops** [laravel-doctrine/orm#456]
When can we expect Laravel 8 support :smiley: 

It's now
```
Problem 1
- Conclusion: remove laravel-doctrine/orm 1.6.1
- Conclusion: don't install laravel-doctrine/orm 1.6.1
- Conclusion: don't install laravel-doctrine/orm 1.6.0
- Installation request for laravel-doctrine/orm 1.6.* -> satisfiable by laravel-doctrine/orm[1.6.0, 1.6.1, 1.6.x-dev].
- Conclusion: don't install laravel/framework v8.0.0
- laravel-doctrine/orm 1.6.x-dev requires illuminate/view ^7.0 -> satisfiable by laravel/framework[v7.27.0]
```

**Comment by barryo** [comment]
Hi @nforced - when? I guess when someone has time to do it. I'm not being facetious here. I think I did it for Laravel 6 or 7 for a bunch of the laravel-doctrine packages because no one else had by the time I needed them. There's plenty of examples of what is required in previous PRs for this. If you're first in the queue for needed this, maybe give it a try?

**Comment by eigan** [comment]
I have pushed the `1.7.0` thanks to @sojeda in #457. Please try it out :+1:

**Comment by 99hops** [comment]
You are the best! Thanks a lot!
@eigan @sojeda :beers:

**Comment by 99hops** [comment]
@eigan Still no luck with dependencies 
https://packagist.org/packages/laravel-doctrine/extensions requires laravel-doctrine/orm: 1.6.*
same for https://packagist.org/packages/laravel-doctrine/migrations :cry:

**Comment by sojeda** [comment]
> @eigan Still no luck with dependencies
> https://packagist.org/packages/laravel-doctrine/extensions requires laravel-doctrine/orm: 1.6.*
> same for https://packagist.org/packages/laravel-doctrine/migrations 😢

Ready 
https://github.com/laravel-doctrine/extensions/pull/51 
https://github.com/laravel-doctrine/migrations/pull/101

**Comment by eigan** [comment]
I have merged the contributions from @sojeda (thanks!). Please try again @nforced.

**Comment by reyphilipregis** [comment]
Still 1.7 doesn't support Laravel 8.

```
Using version ^1.7 for laravel-doctrine/orm
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install laravel-doctrine/orm 1.7.0
    - Conclusion: don't install doctrine/orm 2.8.x-dev
    - Conclusion: don't install doctrine/orm v2.7.3
    - Conclusion: don't install doctrine/orm v2.7.2
    - Conclusion: don't install doctrine/orm v2.7.1
```

**Comment by eigan** [comment]
See answer from @dpslwk which addresses this problem: https://github.com/laravel-doctrine/orm/issues/445#issuecomment-633148110.
